export const SAMPLE_PAYMENT = {
  id: 49415129464909,
  token: '31de0e6d40f8b83d8b1ef0479a968cba',
  cart_token: 'Z2NwLXVzLWVhc3QxOjAxSjBCTTlTTUdFSktSMDYxMUdDOFowNDE3',
  email: null,
  gateway: null,
  buyer_accepts_marketing: false,
  buyer_accepts_sms_marketing: false,
  sms_marketing_phone: null,
  created_at: '2024-06-14T15:01:50+00:00',
  updated_at: '2024-06-14T11:02:41-04:00',
  landing_site: '',
  note: '',
  note_attributes: [],
  referring_site: '',
  shipping_lines: [],
  shipping_address: [],
  taxes_included: false,
  total_weight: 227,
  currency: 'DOP',
  completed_at: null,
  phone: null,
  customer_locale: 'es-DO',
  line_items: [
    {
      key: '40473017778253',
      fulfillment_service: 'manual',
      gift_card: false,
      grams: 227,
      presentment_title: 'Lentes de sol Tipo D',
      presentment_variant_title: 'Negro - D1',
      product_id: 6714553434189,
      quantity: 1,
      requires_shipping: true,
      sku: '1722-1',
      tax_lines: [
        {
          position: 1,
          price: '0.00',
          rate: 0.23,
          title: 'ITBIS',
          source: 'Shopify',
          compare_at: null,
          zone: 'country',
          channel_liable: false,
          identifier: null
        }
      ],
      taxable: false,
      title: 'Lentes de sol Tipo D',
      variant_id: 40473017778253,
      variant_title: 'Negro - D1',
      variant_price: '1000.00',
      vendor: 'SOVEREIGN',
      unit_price_measurement: {
        measured_type: null,
        quantity_value: null,
        quantity_unit: null,
        reference_value: null,
        reference_unit: null
      },
      compare_at_price: null,
      line_price: '1000.00',
      price: '1000.00',
      applied_discounts: [],
      destination_location_id: null,
      user_id: null,
      rank: null,
      origin_location_id: null,
      properties: {}
    }
  ],
  name: '#49415129464909',
  abandoned_checkout_url:
    'https://store.sovereignshades.com/27714617421/checkouts/ac/Z2NwLXVzLWVhc3QxOjAxSjBCTTlTTUdFSktSMDYxMUdDOFowNDE3/recover?key=0bbd274733e0e057bac9b79c034597c9',
  discount_codes: [],
  tax_lines: [
    {
      price: '0.00',
      rate: 0.23,
      title: 'ITBIS'
    }
  ],
  presentment_currency: 'DOP',
  source_name: '12875497473',
  total_line_items_price: '1000.00',
  total_tax: '0.00',
  total_discounts: '0.00',
  subtotal_price: '1000.00',
  total_price: '1000.00',
  total_duties: '0.00',
  device_id: null,
  user_id: null,
  location_id: null,
  source_identifier: null,
  source_url: null,
  source: null,
  closed_at: null
};
